#!/bin/bash

printf "Canonical class generator CPP\n"

echo ""

echo -n "Current Directory : "
pwd

#Variables
PATH=""
CLASS=""
OPTION=""

#PATH
echo "*******************************************************"
echo -ne "\x1b[33mEnter Path Of Creation : \033[m"
read PATH

if [ -d $PATH ] &> /dev/null
then 
	cd $PATH
	echo "Changing Directory to : " $PATH
	echo "*******************************************************"
	echo -ne "\x1b[33mEnter Class Name : \033[m"
	read CLASS
	if [ $CLASS != "" ] 2> /dev/null
	then
		echo "Class Name : " $CLASS
		echo "*******************************************************"
		/bin/mkdir -p includes
		/bin/mkdir -p srcs

		#	***		Printing To Class.hpp	***

		echo "#ifndef _"$CLASS"_HPP_" >> includes/$CLASS.hpp
		echo "#define _"$CLASS"_HPP_" >> includes/$CLASS.hpp
		printf "\n" >> includes/$CLASS.hpp
		echo "#include <iostream>" >> includes/$CLASS.hpp
		printf "\n" >> includes/$CLASS.hpp
		printf "\nclass	$CLASS {
	public:
		$CLASS();
		$CLASS($CLASS const &obj);
		~$CLASS();
		$CLASS &operator=(const $CLASS &obj);

	private:
};\n\n" >> includes/$CLASS.hpp
echo "#endif" >> includes/$CLASS.hpp
		#	***		Printing To Class.cpp	***

		printf "#include \"$CLASS.hpp\"

$CLASS::$CLASS() {
	std::cout << \"$CLASS : Default Constructor Called\" << std::endl;
}

$CLASS::~$CLASS() {
	std::cout << \"$CLASS : Destructor Called\" << std::endl;
}

$CLASS::$CLASS($CLASS const &obj) {
	std::cout << \"$CLASS : Copy Constructor Called\" << std::endl;
	if (this != &obj)
		*this = obj;
}

$CLASS	&$CLASS::operator= (const $CLASS &obj) {
	std::cout << \"$CLASS : Copy Assignment Operator Called\" << std::endl;
	if (this == &obj)
		return *this;
	return (*this);
}\n" > srcs/$CLASS.cpp
		echo -e "\x1b[32m> "$CLASS": Files Created !\033[m\n"
	else
		echo -e "______________________________________\n"
		echo -e "\x1b[31mNo Class Name Entred\033[m\n"
	fi
	else
		echo -e "______________________________________\n"
		echo -e "\x1b[31m*** $PATH : ** Path not found !! **\033[m\n"
fi
